[package]
name = "metaphone3-sys"
version = "0.1.2"
edition = "2024"
license = "MIT"
description = "Bindings for the Metaphone3 Go library"
repository = "https://github.com/kakserpom/metaphone3-rs"
include = ["/lib", "/src", "build.rs"]
[build-dependencies]
cc = "1.0"

[dependencies]